name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
       DOCKER_USER: ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Ubuntu Docker image
      run: docker build . --file Dockerfile-ubuntu --tag onelans/cmd-toolbox:${GITHUB_REF_NAME}-ubuntu
    - name: Publish Ubuntu image to dockerhub
      run: docker push onelans/cmd-toolbox:${GITHUB_REF_NAME}-ubuntu
    - name: Build the Alpine Docker image
      run: docker build . --file Dockerfile-alpine --tag onelans/cmd-toolbox:${GITHUB_REF_NAME}-alpine
    - name: Publish Ubuntu image to dockerhub
      run: docker push onelans/cmd-toolbox:${GITHUB_REF_NAME}-alpine
